### ISSUE TITLE
Field with errors issue

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/validations-with-form_tag-rails#8]
There's a discrepancy between what the validations form_tag lesson shows us to do (<div class="field<%= 'field_with_errors') and what actually works in the following lab (<div class="<%= 'field_with_errors'). It had me hung up for awhile, because its an absolutely new concept, and probably will for others. Just wanted to share.

**Comment by ecssiah** [comment]
meirudick's error seems to have come from the missing space before `field_with_errors`.

```
<div class="field<%= ' field_with_errors' %>" >

VS

<div class="field<%= 'field_with_errors' %>" >
```

The second one will assign a class of `fieldfield_with_errors` instead of assigning two classes `field` and `field_with_errors`.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
