### ISSUE TITLE
Rails Now Appears To Wrap Form Elements With `fields_with_errors` Class Automatically

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/validations-with-form_tag-rails#9]
My application, which is running on Rails 5.2.0 automatically wraps a div with the `fields_with_errors` class around a form element that causes a validation to fail. It doesn't just add the class to an existing div. It actually created a whole new div with this class and wrapped the element.

This no longer has to be done manually, as the lab suggests.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
